config/routes.rb
Rails.application.routes.draw do
  resources :weights
  devise_for :users
  get 'homepage/index'
  get 'homepage/what'
  get 'homepage/body_type'
  get 'homepage/weekly'
  get 'homepage/monthly'
  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :weights
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         	:recoverable, :rememberable, :validatable
end

app/models/weight.rb
class Weight < ApplicationRecord
	belongs_to :user
	GENDER = ["man", "woman"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

	def index
		require 'uri'
		require 'net/http'
		require 'json'

		url = URI("https://api.hurriyet.com.tr/v1/articles?$top=3")

		http = Net::HTTP.new(url.host, url.port)
		http.use_ssl = true
		http.verify_mode = OpenSSL::SSL::VERIFY_NONE

		request = Net::HTTP::Get.new(url)
		request["apikey"] = '61ddc89db26c4c39bbb533d428715aac'
		request["accept"] = 'application/json'
		

		@response = http.request(request)
		@hurriyet = JSON.parse(@response.body)
  	end

  	def what
  	end

  	def body_type
  	end

  	def weekly
  		@weights = Weight.all.order('created_at desc')
  	end

  	def monthly
  		@weights = Weight.all.order('created_at desc')
  	end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /weights
  # GET /weights.json
  def index
    @weights = Weight.all.order('created_at desc')    
  end

  # GET /weights/1
  # GET /weights/1.json
  def show
  end

  # GET /weights/new
  def new
    @weight = current_user.weights.build
  end

  # GET /weights/1/edit
  def edit
  end

  # POST /weights
  # POST /weights.json
  def create
    @weight = current_user.weights.build(weight_params)

    respond_to do |format|
      if @weight.save
        format.html { redirect_to weights_path, notice: 'Weight was successfully created.' }
        format.json { render :show, status: :created, location: @weight }
      else
        format.html { render :new }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weights/1
  # PATCH/PUT /weights/1.json
  def update
    respond_to do |format|
      if @weight.update(weight_params)
        format.html { redirect_to weights_path, notice: 'Weight was successfully updated.' }
        format.json { render :show, status: :ok, location: @weight }
      else
        format.html { render :edit }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weights/1
  # DELETE /weights/1.json
  def destroy
    @weight.destroy
    respond_to do |format|
      format.html { redirect_to weights_url, notice: 'Weight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight
      @weight = Weight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_params
      params.require(:weight).permit(:date, :gender, :lenght, :weight, :ideal_weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/homepage/_footer.html.erb
<!-- Footer  -->
<footer class="fixed-bottom page-footer font-small bg-success ">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3"> 2018 Copyright © 
    
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/homepage/_hurriyet_news.html.erb
<% @hurriyet.each do |a| %>
	
	<center>
		 <div class="card" style="width: 60rem;">
		  <div class="card-body">
		    <h5 class="card-title"><%= a["Title"]%></h5>
		    <p class="card-text"><%= a["Description"]%></p>
		    <a href="<%= a["Url"]%>" class="btn btn-primary">Habere git</a>
		  </div>
		</div>
		<br>
	</center>
    
   
  <% end %>

<br>

app/views/homepage/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-light">
  <a class="navbar-brand bg-light" <%= link_to 'K.T.S', root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      	<% if !user_signed_in? %>
        	
        <% else %>
        	<a class="nav-link bg-light" <%= link_to 'Follow up', weights_path %> </a>
        <% end %>

      </li>
      <a class="nav-link bg-light" <%= link_to 'Body Type', homepage_body_type_path %> </a>
    </ul>
    <li class="form-inline my-2">
      <a class="nav-link bg-light" <%= link_to 'About', homepage_what_path %> </a>
    	<% if !user_signed_in? %>
	    	<a class="nav-link bg-light" <%= link_to 'Sign up', new_user_registration_path %> </a>
	    	<a class="nav-link bg-light" <%= link_to 'Log in', new_user_session_path %>   </a>
	    <% else %>
      <a class="nav-link bg-light" <%= link_to 'Edit Profile', edit_user_registration_path %></a>
	    	<a class="nav-link bg-light" <%= link_to 'Log out', destroy_user_session_path, :method => :delete %> </a>
	    <% end %>
    </li>      

  </div>
</nav>

app/views/homepage/body_type.html.erb
<ul>
	<center>
		<img src="https://www.hesaplama.net/images/vki.gif" alt="Vücut Kitle Endeksi Tablosu">
		<h3>How is the Body Mass Index calculated?</h3>
	</center>
	

	<p>Body mass index is obtained by dividing your body weight by the square of your height. As a result, the body mass index is evaluated in the following intervals.
	</p>

	<h6 class="font-weight-bold">Weak</h6>

	<p>Indicates that you are not in the proper weight according to your height and that you are weak. Weakness is a risky and undesirable condition for some diseases. You should be well-balanced and balanced to reach the appropriate weight for your height and take care to improve your eating habits.</p>
	<h6 class="font-weight-bold">Normal</h6>

	<p>Indicates that you have the appropriate weight according to your height. Take care to protect your weight by having adequate and balanced nutrition and regular physical activity.</p>
	<h6 class="font-weight-bold">Overweight</h6>

	<p>Indicates your body weight is higher than your height. Overweight leads to obesity (obesity), which is a risk factor for many diseases unless the necessary precautions are taken.</p>
	<h6 class="font-weight-bold">Fat (Obese) - Class I</h6>

	<p>According to your height, your body weight is overweight, in other words, is an indication that you are fat. Obesity, cardiovascular diseases, diabetes, hypertension, etc. are risk factors for chronic diseases. It is very important for your health to go to a health facility by decreasing in the control of a physician / dietician. Please contact your health care provider.</p>
	<h6 class="font-weight-bold">Fat (Obese) - II. Class</h6>

	<p>According to your height, your body weight is overweight, in other words, is an indication that you are fat. Obesity, cardiovascular diseases, diabetes, hypertension, etc. are risk factors for chronic diseases. It is very important for your health to go to a health facility by decreasing in the control of a physician / dietician. Please contact your health care provider.</p>

	<h6 class="font-weight-bold">Overweight (Over Obese) - III. Class</h6>

	<p>According to your height, your body weight is overweight, in other words, is an indication that you are fat. Obesity, cardiovascular diseases, diabetes, hypertension, etc. are risk factors for chronic diseases. It is very important for your health to go to a health facility by decreasing in the control of a physician / dietician. Please contact your health care provider.</p>

	<h2>
		<%= link_to 'Resources', href="https://vucut-kitle-endeksi.hesaplama.net/"%>
	</h2>

	
	

</ul>

app/views/homepage/index.html.erb
<br>
<%= render 'hurriyet_news' %>

app/views/homepage/monthly.html.erb
<center>
  <div class="col-md-10 col-md-offset-1">
  <center>
    <h1> 1 Month History </h1> 
  </center>
  <table class="table table-info">
      <thead>
        <tr>
          
        </tr>
      </thead>
    </table>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">username email</th>
          <th scope="col">Date</th>
          <th scope="col">Hour</th>
          <th scope="col">Gender</th>
          <th scope="col">Lenght</th>
          <th scope="col">Weight</th>
          <th scope="col">Ideal weight</th>
          <th scope="col">Variation</th>
          <th scope="col">Body Type</th>
         
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @weights.each do |weight| %>
          <tr>
            <% if weight.date >= 1.month.ago %>
              <% if current_user.id == weight.user_id %>
                <td><%= weight.user.email%></td>
                <% t = weight.date %>
                <td><%= t.strftime("%d %B %Y (%A)")%> </td> 
                <td><%= weight.created_at.strftime("%R")%> </td>
                <td><%= weight.gender %></td>
                <td><%= weight.lenght %></td>
                <td><%= weight.weight %></td>
                <% if weight.gender == "man"  %>
                  <td><%= a = (50 + (2.3 ) * ((weight.lenght - 152.2) / 2.54)).round(1) %></td>
                  <td><%= (weight.weight - a).round(1)  %></td>
                <% else weight.gender == "woman" %>
                  <td><%= a = (45.5 + (2.3 ) * ((weight.lenght - 152.2) / 2.54)).round(1) %></td>
                  <td><%= (weight.weight - a).round(1)  %></td>

                <% end %>
                <% a=weight.lenght/100%>
                <% x=(weight.weight)/(a*a) %>
                <% if(x<=18.5) %>
                  <td>Weak</td>
                <% elsif(x>18.5 && x<=24.9) %>
                  <td>Normal</td>
                <% elsif(x>24.9 && x<=29.9) %>
                  <td>Overweight</td>
                <% elsif(x>29.9 && x<=34.9) %>
                  <td>Obese (Class I)</td>
                <% elsif(x>34.9 && x<=39.9) %>
                  <td>Obese (Class II)</td>
                <% else %>
                  <td>Obese (Class III)</td>
                <% end -%>
                <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
                <td><%= link_to 'Destroy', weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            <% end -%>
          </tr>
        <% end %>
      </tbody>
    </table>



  <center >
    <%= link_to 'Back', :back, class:"btn bg-info" %>
    </br>
    </br>
    </br>
     </br>
    </br>
  </center>
  </div>
</center>

app/views/homepage/weekly.html.erb
<center>
  <div class="col-md-10 col-md-offset-1">
  <center>
    <h1> 1 Week History </h1> 
  </center>
    <table class="table table-info">
      <thead>
        <tr>
          
        </tr>
      </thead>
    </table>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">username email</th>
          <th scope="col">Date</th>
          <th scope="col">Hour</th>
          <th scope="col">Gender</th>
          <th scope="col">Lenght</th>
          <th scope="col">Weight</th>
          <th scope="col">Ideal weight</th>
          <th scope="col">Variation</th>
          <th scope="col">Body Type</th>
         
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @weights.each do |weight| %>
          <tr>
            <% if weight.date >= 1.week.ago %>
              <% if current_user.id == weight.user_id %>
                <td><%= weight.user.email%></td>
                <% t = weight.date %>
                <td><%= t.strftime("%d %B %Y (%A)")%> </td> 
                <td><%= weight.created_at.strftime("%R")%> </td>
                <td><%= weight.gender %></td>
                <td><%= weight.lenght %></td>
                <td><%= weight.weight %></td>
                <% if weight.gender == "man"  %>
                  <td><%= a = (50 + (2.3 ) * ((weight.lenght - 152.2) / 2.54)).round(1) %></td>
                  <td><%= (weight.weight - a).round(1)  %></td>
                <% else weight.gender == "woman" %>
                  <td><%= a = (45.5 + (2.3 ) * ((weight.lenght - 152.2) / 2.54)).round(1) %></td>
                  <td><%= (weight.weight - a).round(1)  %></td>

                <% end %>
                <% a=weight.lenght/100%>
                <% x=(weight.weight)/(a*a) %>
                <% if(x<=18.5) %>
                  <td>Weak</td>
                <% elsif(x>18.5 && x<=24.9) %>
                  <td>Normal</td>
                <% elsif(x>24.9 && x<=29.9) %>
                  <td>Overweight</td>
                <% elsif(x>29.9 && x<=34.9) %>
                  <td>Obese (Class I)</td>
                <% elsif(x>34.9 && x<=39.9) %>
                  <td>Obese (Class II)</td>
                <% else %>
                  <td>Obese (Class III)</td>
                <% end -%>
                <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
                <td><%= link_to 'Destroy', weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            <% end -%>
          </tr>
        <% end %>
      </tbody>
    </table>



  <center >
    <%= link_to 'Back', :back, class:"btn bg-info" %>
    </br>
    </br>
    </br>
     </br>
    </br>
  </center>
  </div>
</center>

app/views/homepage/what.html.erb
<center>
    <div class="col-md-10 col-md-offset-1">
        <div class="card" style="width: 68rem; height: 30rem;">
          <div class="card-body">
            
            <h1 class="card-title">What's about ?</h5>
            
            <h6 class="card-subtitle mb-2 text-muted"></h6>
            <p class="card-text">Kullanıcıların kilo ve boylarını girerek ideal kilolarını hesaplayan web uygulamasıdır.</p>
            
            <h5>kullanılan teknolojiler</h5>
            
            <p>Ruby on Rails</p>
            <p>Bootstrap</p>
            <p>Heroku</p>
            <p>Postgresql</p>
            

            <h5>Eklenecekler</h5>
            
            <p>Haftalık ve Aylık kilo farkı</p>
            <p>Haftalık ve Aylık listeyi pdf formatına çevirme</p>
            <p>Kullanıcı mailllerini kontrol etme ve onaylama </p>
            
            

          </div>
        </div>
    </div>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KTS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/homepage/navbar' %>
    <%= yield %>
  </body>
</html>
<%= render '/homepage/footer' %>

app/views/weights/_form.html.erb
<center>
  <div class="col-md-10 col-md-offset-1">
    <%= simple_form_for(@weight) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :date %>
      </div>
      <div class="dropdown ">
          <%= f.label :gender %>
          <%= f.select(:gender, Weight::GENDER)  %>   
        </div>
        
      </div>
      <br>
      <br>

        
      <div class="form-inputs" style="width: 69rem;>
        <%= f.input :lenght, :placeholder => "example 180.5" %>
      </div>

      <div class="form-inputs" style="width: 69rem;>
        <%= f.input :weight, :placeholder => "example 80.6" %>
      </div>

      <br>   
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>
</center>

app/views/weights/edit.html.erb
<center>
	<h1>Editing Weight</h1>

	<%= render 'form', weight: @weight %>

	<br>
	<%= link_to 'Back', weights_path %>
</center>

app/views/weights/index.html.erb
<center>
  <div class="col-md-10 col-md-offset-1">
  <center>
    <h1>Weights</h1>
  </center>


    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">username email</th>
          <th scope="col">Date</th>
          <th scope="col">Hour</th>
          <th scope="col">Gender</th>
          <th scope="col">Lenght</th>
          <th scope="col">Weight</th>
          <th scope="col">Ideal weight</th>
          <th scope="col">Variation</th>
          <th scope="col">Body Type</th>
         
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @weights.each do |weight| %>
          <tr>
            <% if current_user.id == weight.user_id %>
              <td><%= weight.user_id%></td>
              <% t = weight.date %>
              <td><%= t.strftime("%d %B %Y (%A)")%> </td> 
              <td><%= weight.created_at.strftime("%R")%> </td>
              <td><%= weight.gender %></td>
              <td><%= weight.lenght %></td>
              <td><%= weight.weight %></td>
              <% if weight.gender == "man"  %>
                <td><%= a = (50 + (2.3 ) * ((weight.lenght - 152.2) / 2.54)).round(1) %></td>
                <td><%= (weight.weight - a).round(1)  %></td>
              <% else weight.gender == "woman" %>
                <td><%= a = (45.5 + (2.3 ) * ((weight.lenght - 152.2) / 2.54)).round(1) %></td>
                <td><%= (weight.weight - a).round(1)  %></td>

              <% end %>
              <% a=weight.lenght/100%>
              <% x=(weight.weight)/(a*a) %>
              <% if(x<=18.5) %>
                <td>Weak</td>
              <% elsif(x>18.5 && x<=24.9) %>
                <td>Normal</td>
              <% elsif(x>24.9 && x<=29.9) %>
                <td>Overweight</td>
              <% elsif(x>29.9 && x<=34.9) %>
                <td>Obese (Class I)</td>
              <% elsif(x>34.9 && x<=39.9) %>
                <td>Obese (Class II)</td>
              <% else %>
                <td>Obese (Class III)</td>
              <% end -%>
              <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
              <td><%= link_to 'Destroy', weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>


    <div class="text-right">
      <%= link_to 'Weekly', homepage_weekly_path, class:"btn bg-info" %>
      <%= link_to 'Monthly', homepage_monthly_path, class:"btn bg-info" %>
    </div>

  <center >
    <%= link_to 'New Weight', new_weight_path, class:"btn bg-light" %>
    </br>
    </br>
    </br>
     </br>
    </br>
  </center>
  </div>
</center>

app/views/weights/new.html.erb
<center>
	<h1>New Weight</h1>

	<%= render 'form', weight: @weight %>

	<%= link_to 'Back', weights_path %>
</center>

app/views/weights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @weight.date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @weight.gender %>
</p>

<p>
  <strong>Lenght:</strong>
  <%= @weight.lenght %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @weight.weight %>
</p>

<p>
  <strong>Ideal weight:</strong>
  <% @weight.weight %>
</p>
<p>
  <strong>Body Type:</strong>
 	<% @x %>
</p>

<%= link_to 'Edit', edit_weight_path(@weight) %> |
<%= link_to 'Back', weights_path %>